server:
  address: 0.0.0.0
  port: 8083

  tomcat:
    basedir: servlet
    accesslog:
      enabled: true
      directory: logs
      pattern: '%h %l %u %t "%r" %s %b %D'


spring:
  application:
    name: serviceBuy

  cloud:
    consul:
      host: 192.168.1.45
      port: 80

      discovery:
        preferIpAddress: true
        heartbeat:
          enabled: true
          ttlValue: 60
          ttlUnit: s

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.sleuth.log: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.consul: TRACE

